(function(){var U=function(f){return "https://commons.wikimedia.org/wiki/Special:FilePath/"+encodeURIComponent(f)+"?width=1280"};
var E=window.EARTH_ERAS.find(function(x){return x.id==="big-bang"});if(E){E.titleFa="آغاز زمان";E.yearLabelFa="۱۳٫۸ میلیارد سال پیش";E.epochFa="خاستگاه کیهانی";E.images=[{src:U("CMB_Timeline300_no_WMAP.jpg"),cap:"Cosmic timeline / NASA",capFa:"خط زمان کیهان — ناسا"},{src:U("Ilc_9yr_moll4096.png"),cap:"CMB / NASA",capFa:"تابش زمینهٔ کیهانی — ناسا"},{src:U("Hubble_ultra_deep_field.jpg"),cap:"Hubble Ultra Deep Field",capFa:"میدان فراژرف هابل"},{src:U("Andromeda_Galaxy_(with_h-alpha).jpg"),cap:"Andromeda Galaxy",capFa:"کهکشان آندرومدا"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="earth-forms"});if(E){E.titleFa="شکل‌گرفتن زمین";E.yearLabelFa="۴٫۵۴ میلیارد سال پیش";E.epochFa="آغاز هادئن";E.images=[{src:U("Artist's_concept_of_collision_at_HD_172555.jpg"),cap:"Giant impact / NASA",capFa:"طرح برخورد بزرگ — ناسا"},{src:U("Moon_and_Earth.jpg"),cap:"Moon and Earth",capFa:"ماه و زمین"},{src:U("FullMoon2010.jpg"),cap:"The Moon today",capFa:"ماه امروز"},{src:U("Hadean.png"),cap:"Hadean Earth",capFa:"بازسازی زمین هادئن"},{src:U("Protoplanetary_disk.jpg"),cap:"Protoplanetary disk",capFa:"قرص پیش‌سیاره‌ای"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="archean-life"});if(E){E.titleFa="جهان آب و نخستین زندگی";E.yearLabelFa="۳٫۵ میلیارد سال پیش";E.epochFa="آرکئن";E.images=[{src:U("Stromatolites_in_Sharkbay.jpg"),cap:"Living stromatolites",capFa:"استروماتولیت زنده"},{src:U("Stromatolite.jpg"),cap:"Fossil stromatolite",capFa:"استروماتولیت فسیلی"},{src:U("Cyanobacteria.jpg"),cap:"Cyanobacteria",capFa:"سیانوباکتری"},{src:U("Archean.png"),cap:"Archean Earth",capFa:"بازسازی آرکئن"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="great-oxidation"});if(E){E.titleFa="اکسیژن سیاره را عوض می‌کند";E.yearLabelFa="۲٫۴ میلیارد سال پیش";E.epochFa="اکسایش بزرگ";E.images=[{src:U("Banded_iron_formation_Dales_Gorge.jpg"),cap:"Banded iron",capFa:"سازند آهن نواری"},{src:U("BIFs.jpg"),cap:"BIF close-up",capFa:"نمای نزدیک آهن نواری"},{src:U("Snowball_Huronian.jpg"),cap:"Huronian snowball",capFa:"یخبندان هورونی"},{src:U("Hematite.jpg"),cap:"Hematite",capFa:"هماتیت"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="cambrian"});if(E){E.titleFa="تابش کامبرین";E.yearLabelFa="۵۲۰ میلیون سال پیش";E.epochFa="کامبرین";E.images=[{src:U("Opabinia_regalis.png"),cap:"Opabinia",capFa:"اوپابینیا"},{src:U("Anomalocaris_canadensis.jpg"),cap:"Anomalocaris",capFa:"آنومالوکاریس"},{src:U("Trilobite_fossil.jpg"),cap:"Trilobite",capFa:"فسیل تریلوبیت"},{src:U("Marrella.jpg"),cap:"Marrella",capFa:"مارلا"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="jurassic"});if(E){E.titleFa="پانگه‌آ می‌شکند، دایناسورها فرمان می‌رانند";E.yearLabelFa="۱۶۰ میلیون سال پیش";E.epochFa="ژوراسیک پسین";E.images=[{src:U("Allosaurus_fragilis.png"),cap:"Allosaurus",capFa:"آلوسور"},{src:U("Archaeopteryx_lithographica_replica.jpg"),cap:"Archaeopteryx",capFa:"آرکئوپتریکس"},{src:U("Diplodocus_carnegii.jpg"),cap:"Diplodocus",capFa:"دیپلودوکوس"},{src:U("Plesiosaurus.jpg"),cap:"Plesiosaur",capFa:"پلسیوسور"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="cretaceous"});if(E){E.titleFa="دریاهای بلند و گل‌ها";E.yearLabelFa="۹۰ میلیون سال پیش";E.epochFa="کرتاسه پسین";E.images=[{src:U("Tyrannosaurus_rex_Sue.jpg"),cap:"T. rex Sue",capFa:"تی‌رکس، سو"},{src:U("Triceratops_skull.jpg"),cap:"Triceratops",capFa:"جمجمهٔ تریسراتوپس"},{src:U("Amber_with_inclusions.jpg"),cap:"Amber",capFa:"کهربا"},{src:U("Mosasaurus_hoffmannii.jpg"),cap:"Mosasaur",capFa:"موزاسور"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="lgm"});if(E){E.titleFa="آخرین بیشینهٔ یخچالی";E.yearLabelFa="۲۱ هزار سال پیش";E.epochFa="پلیستوسن";E.images=[{src:U("Woolly_mammoth.jpg"),cap:"Woolly mammoth",capFa:"ماموت پشمی"},{src:U("Smilodon_fatalis.jpg"),cap:"Smilodon",capFa:"اسمایلودون"},{src:U("Lascaux_painting.jpg"),cap:"Lascaux",capFa:"هنر غار لاسکو"},{src:U("Glacier.jpg"),cap:"Glacier",capFa:"یخچال"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="present"});if(E){E.titleFa="سیارهٔ اندازه‌گیری‌شده";E.yearLabelFa="۲۰۲۶ میلادی";E.epochFa="اکنون";E.images=[{src:U("The_Earth_seen_from_Apollo_17.jpg"),cap:"Earth from Apollo 17 / NASA",capFa:"زمین از آپولو ۱۷ — ناسا"},{src:U("Blue_Marble_2002.png"),cap:"Blue Marble / NASA",capFa:"مرمر آبی — ناسا"},{src:U("Earth_at_Night.jpg"),cap:"Earth at night / NASA",capFa:"زمین در شب — ناسا"}];}
var E=window.EARTH_ERAS.find(function(x){return x.id==="plus10"});if(E){E.titleFa="آینده نزدیک — یک سناریو";E.yearLabelFa="۲۰۳۶ میلادی";E.epochFa="سناریو";E.images=[{src:U("Bleached_coral.jpg"),cap:"Bleached coral",capFa:"مرجان سفیدشده"},{src:U("Wildfire_near_Yosemite.jpg"),cap:"Wildfire",capFa:"آتش‌سوزی جنگل"},{src:U("Drought.jpg"),cap:"Drought",capFa:"خشکسالی"}];}
})();
